/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qihoo_apitest_crash_NativeCrashHandler */

#ifndef _Included_com_qihoo_apitest_crash_NativeCrashHandler
#define _Included_com_qihoo_apitest_crash_NativeCrashHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qihoo_apitest_crash_NativeCrashHandler
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qihoo_apitest_crash_NativeCrashHandler_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_qihoo_apitest_crash_NativeCrashHandler
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qihoo_apitest_crash_NativeCrashHandler_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_qihoo_apitest_crash_NativeCrashHandler
 * Method:    invideCrash
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_qihoo_apitest_crash_NativeCrashHandler_invideCrash
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
